Add item requests
UlyanaVasilieva/java-shareit pull request #3
Opened 2023-10-21 10:59 UTC by UlyanaVasilieva

2023-10-26 20:34 UTC, PolnySkvorets commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final ItemRepository itemRepository;
Для ItemService здесь слишком много логики для других сущностей, лучше сделать отдельные сервисы для User, Comment... и работать через их методы, а не все разом внутри одного сервиса.

2023-10-26 20:39 UTC, PolnySkvorets requested changes
Привет! оставил один комментарий, но он относится и к другим сервисам. Попробуй разделять логику по сервисам, по сущностям. Иначе получается дублирование или путаница при проверке.

2023-10-27 21:56 UTC, UlyanaVasilieva commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final ItemRepository itemRepository;
Исправила. Единственное, я не трогала 2 метода с комментариями, которые находятся в ItemService, так как в ТЗ 14 спринта сказано, что "Для получения списка из БД реализуйте обращение к новому репозиторию CommentRepository в соответствующих методах в ItemServiceImpl . "

2023-10-28 21:59 UTC, PolnySkvorets approved these changes
привет! Теперь всё отлично

2023-10-30 07:01 UTC, merged